### PR TITLE
WIP: task notification

### PR DESCRIPTION
**Pull request by mkmark**
Only basic adding now.

### CODE REVIEW

**Comment by Essoz** [comment]
Hi Mark! Thank you so much for working on this. 

Converting this to WIP so that we don't have to merge it right now.

**Comment by mkmark** [comment]
Well, it's working now, alarm added when task set, alarm deleted when task deleted.

**Comment by Essoz** [comment]
I see.

lgtm

@PhyllisJu what do you think?

**Comment by PhyllisJu** [comment]
Hi Mark! Thanks so much for your contribution.
I will run the code tomorrow and tell you if I have any questions :)

**Comment by mkmark** [comment]
> So when the browser is restarted, alarms can still be triggered at the correct time right?

Yes

**Pull request merged**
